/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.jmoordbcore.processor.example.repository;

import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import com.jmoordb.core.annotation.enumerations.JakartaSource;
import com.jmoordb.core.annotation.enumerations.TypePK;
import com.jmoordb.core.annotation.repository.Repository;
import com.jmoordb.core.repository.RepositoryCrud;
import com.jmoordbcore.processor.example.model.Profesion;

/**
 *
 * @author avbravo
 */
@Repository(entity = Profesion.class, fieldPk ="idprofesion", typePK = TypePK.LONG
        ,autogeneratedActive = AutogeneratedActive.ON,
        database = "{mongodb.database", collection = "profesion", jakartaSource =JakartaSource.JAKARTA )
public interface ProfesionRepository extends RepositoryCrud<Profesion, Long>{
//    @Save
//   public Optional<Profesion> save(Profesion profesion);
//    
}
