/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.jmoordbcore.processor.example.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import com.jmoordb.core.annotation.enumerations.TypePK;
import java.util.List;
import java.util.Set;

/**
 *
 * @author avbravo
 */
@Entity
public class ProfesionSet {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idprofesion;
    @Column
    private String profesion;
    @Referenced(from = "grupoprofesion", localField = "grupoprofesion.idgrupoprofesion", 
            foreignField = "idgrupoprofesion", as = "grupoprofesion", typePK = TypePK.STRING)
    private Set<Grupoprofesion> grupoprofesion;

    public ProfesionSet() {
    }

    public Long getIdprofesion() {
        return idprofesion;
    }

    public void setIdprofesion(Long idprofesion) {
        this.idprofesion = idprofesion;
    }

  

   

    public String getProfesion() {
        return profesion;
    }

    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }

    public Set<Grupoprofesion> getGrupoprofesion() {
        return grupoprofesion;
    }

    public void setGrupoprofesion(Set<Grupoprofesion> grupoprofesion) {
        this.grupoprofesion = grupoprofesion;
    }

   

   
    
}
