/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.jmoordbcore.processor.example.model;

import com.jmoordb.core.annotation.Column;
import com.jmoordb.core.annotation.Embedded;
import com.jmoordb.core.annotation.Entity;
import com.jmoordb.core.annotation.Id;
import com.jmoordb.core.annotation.Referenced;
import com.jmoordb.core.annotation.enumerations.AutogeneratedActive;
import com.jmoordb.core.annotation.enumerations.TypePK;
import com.jmoordb.core.annotation.enumerations.TypeReferenced;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;
import org.bson.types.ObjectId;

/**
 *
 * @author avbravo
 */
@Entity
public class Tiposdatos {

    @Id(autogeneratedActive = AutogeneratedActive.ON)
    private Long idtiposdatos;

    @Column
    private Double saldo;
    @Column
    private Integer edad;
    @Column
    private Date fecha;
    @Column
    private Boolean activo;
    @Column
    private ObjectId objectId;
    @Column
    private Float flotante;
    @Column
    private int intprimitivo;
    @Column
    private List<String> apodos;
    @Column
    private List<Double> ventas;
    @Column
    private Set<String> deportes;
    @Column
    private Stream<String> valores;
    @Embedded
    private Idioma idioma;

    @Embedded
    private List<Musica> musica;
    @Embedded
    private Set<Persona> persona;

    @Embedded
    private Stream<Corregimiento> corregimiento;

    @Referenced(from = "oceano", localField = "oceano.idoceano", foreignField = "idplaneta", as = "oceano", typePK = TypePK.STRING)
    private Oceano oceano;
    @Referenced(from = "idprofesion", localField = "profesion.idprofesion", foreignField = "idprofesion", as = "profesion", typePK = TypePK.LONG)
    private Profesion profesion;
    @Referenced(from = "planeta", localField = "planeta.idplaneta", foreignField = "idplaneta", as = "planeta", typePK = TypePK.STRING)
    private List<Planeta> planeta;

    @Referenced(from = "grupoprofesion", localField = "grupoprofesion.idgrupoprofesion",
            foreignField = "idgrupoprofesion", as = "grupoprofesion",
            typePK = TypePK.STRING)
    private Stream<Grupoprofesion> grupoprofesion;
   

    @Referenced(from = "edificio", localField = "edificio.idedificio",
            foreignField = "idedificio", as = "edificio",
            typePK = TypePK.LONG,
            typeReferenced = TypeReferenced.REFERENCED)
    private Set<Edificio> edificio;

    public List<Planeta> getPlaneta() {
        return planeta;
    }

    public void setPlaneta(List<Planeta> planeta) {
        this.planeta = planeta;
    }

    public Set<Edificio> getEdificio() {
        return edificio;
    }

    public void setEdificio(Set<Edificio> edificio) {
        this.edificio = edificio;
    }

    public Oceano getOceano() {
        return oceano;
    }

    public void setOceano(Oceano oceano) {
        this.oceano = oceano;
    }

    public Stream<Grupoprofesion> getGrupoprofesion() {
        return grupoprofesion;
    }

    public void setGrupoprofesion(Stream<Grupoprofesion> grupoprofesion) {
        this.grupoprofesion = grupoprofesion;
    }

    public Set<Persona> getPersona() {
        return persona;
    }

    public void setPersona(Set<Persona> persona) {
        this.persona = persona;
    }

    public Stream<Corregimiento> getCorregimiento() {
        return corregimiento;
    }

    public void setCorregimiento(Stream<Corregimiento> corregimiento) {
        this.corregimiento = corregimiento;
    }

    public int getIntprimitivo() {
        return intprimitivo;
    }

    public void setIntprimitivo(int intprimitivo) {
        this.intprimitivo = intprimitivo;
    }

    public List<Musica> getMusica() {
        return musica;
    }

    public void setMusica(List<Musica> musica) {
        this.musica = musica;
    }

    public Set<String> getDeportes() {
        return deportes;
    }

    public void setDeportes(Set<String> deportes) {
        this.deportes = deportes;
    }

    public Stream<String> getValores() {
        return valores;
    }

    public void setValores(Stream<String> valores) {
        this.valores = valores;
    }

    public Float getFlotante() {
        return flotante;
    }

    public void setFlotante(Float flotante) {
        this.flotante = flotante;
    }

    public List<String> getApodos() {
        return apodos;
    }

    public void setApodos(List<String> apodos) {
        this.apodos = apodos;
    }

    public List<Double> getVentas() {
        return ventas;
    }

    public void setVentas(List<Double> ventas) {
        this.ventas = ventas;
    }

    public Tiposdatos() {
    }

    public ObjectId getObjectId() {
        return objectId;
    }

    public void setObjectId(ObjectId objectId) {
        this.objectId = objectId;
    }

    public Boolean getActivo() {
        return activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    public Long getIdtiposdatos() {
        return idtiposdatos;
    }

    public void setIdtiposdatos(Long idtiposdatos) {
        this.idtiposdatos = idtiposdatos;
    }

    public Double getSaldo() {
        return saldo;
    }

    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }

    public Integer getEdad() {
        return edad;
    }

    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Profesion getProfesion() {
        return profesion;
    }

    public void setProfesion(Profesion profesion) {
        this.profesion = profesion;
    }

    public Idioma getIdioma() {
        return idioma;
    }

    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }

}
